import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Badge, Card } from '../components/ui'
import { scoped } from '../lib/selectors'
import { useMesh } from '../state/MeshContext'
import type { Shift } from '../types'

export function NursePage() {
  const { state, person, session } = useMesh()
  const [shift, setShift] = useState<Shift>(person?.shift ?? 'day')
  if (!person || !session) return null
  const patients = scoped(state.patients, session.hospitalId).filter((p) => p.bed)
  const tasks = [
    { title: 'Check vitals', who: patients[1]?.name ?? 'Bed 02', when: '10:00 AM' },
    { title: 'Medication reminder', who: patients[0]?.name ?? 'Bed 01', when: '12:00 PM' },
  ]
  return (
    <div className="space-y-4 px-5 pt-2">
      <div>
        <p className="text-xl font-extrabold">Nurse Station</p>
        <p className="text-xs text-muted">{person.name}</p>
      </div>
      <div className="grid grid-cols-2 gap-2 rounded-2xl bg-white p-1 card-shadow">
        <button
          type="button"
          className={`rounded-xl py-2 text-xs font-bold ${shift === 'day' ? 'bg-brand text-white' : 'text-muted'}`}
          onClick={() => setShift('day')}
        >
          Day Shift (7AM - 7PM)
        </button>
        <button
          type="button"
          className={`rounded-xl py-2 text-xs font-bold ${shift === 'night' ? 'bg-brand text-white' : 'text-muted'}`}
          onClick={() => setShift('night')}
        >
          Night Shift (7PM - 7AM)
        </button>
      </div>
      <div className="flex items-center justify-between">
        <h2 className="font-extrabold">Assigned Patients ({patients[0]?.ward ?? 'Ward'})</h2>
        <Link to="/app/patients" className="text-xs font-semibold text-brand">
          View all
        </Link>
      </div>
      <div className="space-y-2">
        {patients.map((p) => (
          <Card key={p.id} className="flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-brand">Bed {p.bed}</p>
              <p className="font-bold">{p.name}</p>
              <p className="text-xs text-muted">
                {p.condition} · {p.temp?.includes('101') ? 'Fever' : p.condition}
              </p>
            </div>
            <Badge tone={p.temp?.includes('101') ? 'amber' : 'green'}>
              {p.temp?.includes('101') ? 'Monitoring' : 'Stable'}
            </Badge>
          </Card>
        ))}
      </div>
      <h2 className="font-extrabold">Nursing Tasks</h2>
      {tasks.map((task) => (
        <Card key={task.title} className="flex items-center justify-between">
          <div>
            <p className="font-bold">{task.title}</p>
            <p className="text-xs text-muted">{task.who}</p>
          </div>
          <span className="text-xs font-semibold text-brand">Due {task.when}</span>
        </Card>
      ))}
    </div>
  )
}

export function HandoverPage() {
  const { state, person, session, dispatch } = useMesh()
  const [shift, setShift] = useState<Shift>(person?.shift ?? 'day')
  const [form, setForm] = useState({ watchlist: '', pendingLabs: '', medsDue: '', staffingNote: '' })
  if (!person || !session) return null
  const other: Shift = shift === 'day' ? 'night' : 'day'
  const notes = scoped(state.handovers, session.hospitalId)
  const incoming = notes.filter((h) => h.shift === other)
  const latest = incoming[0]
  return (
    <div className="space-y-4 px-5 pt-2">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-extrabold">Shift Handover (AI Summary)</h1>
        <span className="text-[10px] font-bold text-brand">Generated by AI</span>
      </div>
      <div className="grid grid-cols-2 gap-2 rounded-2xl bg-white p-1 card-shadow">
        <button type="button" className={`rounded-xl py-2 text-xs font-bold ${shift === 'day' ? 'bg-brand text-white' : 'text-muted'}`} onClick={() => setShift('day')}>
          Day
        </button>
        <button type="button" className={`rounded-xl py-2 text-xs font-bold ${shift === 'night' ? 'bg-brand text-white' : 'text-muted'}`} onClick={() => setShift('night')}>
          Night
        </button>
      </div>
      {latest ? (
        <Card>
          <p className="text-sm font-extrabold">
            {latest.shift === 'night' ? 'Night to Day' : 'Day to Night'} Shift
          </p>
          <p className="mt-3 text-xs font-bold text-muted">Key Points</p>
          <ul className="mt-1 list-disc space-y-1 pl-4 text-sm">
            <li>{latest.watchlist}</li>
            <li>{latest.pendingLabs}</li>
            <li>{latest.medsDue}</li>
          </ul>
          <p className="mt-3 text-xs font-bold text-muted">Pending Tasks</p>
          <p className="text-sm">{latest.staffingNote}</p>
          <p className="mt-3 text-xs text-muted">Please review and confirm the handover before shift change.</p>
        </Card>
      ) : (
        <p className="text-sm text-muted">No incoming report yet.</p>
      )}
      <div className="grid gap-2">
        <Field label="Patients to watch" value={form.watchlist} onChange={(v) => setForm({ ...form, watchlist: v })} />
        <Field label="Pending labs" value={form.pendingLabs} onChange={(v) => setForm({ ...form, pendingLabs: v })} />
        <Field label="Meds due" value={form.medsDue} onChange={(v) => setForm({ ...form, medsDue: v })} />
        <Field label="Staffing" value={form.staffingNote} onChange={(v) => setForm({ ...form, staffingNote: v })} />
      </div>
      <div className="flex gap-2">
        <button
          type="button"
          className="flex-1 rounded-2xl bg-white py-3 text-sm font-bold card-shadow"
          onClick={() =>
            dispatch({
              type: 'add-handover',
              handover: { hospitalId: session.hospitalId, shift, authorId: person.id, ...form },
            })
          }
        >
          Edit / Save
        </button>
        <button
          type="button"
          className="flex-1 rounded-2xl bg-brand py-3 text-sm font-bold text-white"
          onClick={() => {
            const mine = notes.find((h) => h.authorId === person.id && !h.signed)
            if (mine) dispatch({ type: 'sign-handover', handoverId: mine.id })
          }}
        >
          Confirm
        </button>
      </div>
    </div>
  )
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <label className="block text-xs font-semibold">
      {label}
      <textarea className="mt-1 w-full rounded-xl border border-line bg-white p-2 text-sm" rows={2} value={value} onChange={(e) => onChange(e.target.value)} />
    </label>
  )
}
